#GET http://localhost:5101/games/5
####
GET http://localhost:5101/games/

###
POST http://localhost:5101/games/
Content-Type: application/json

{
  "Name": "awesomoxs2",
  "GenreId": 1,
  "Price": 25.99,
  "ReleaseDate": "2022-06-30"
}

###
PUT http://localhost:5101/games/2
Content-Type: application/json

{
  "Name": "An Excellent movie part2",
  "GenreId": 1,
  "Price": 12.99,
  "ReleaseDate": "2022-06-30"
}

###
DELETE http://localhost:5101/games/2